/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpointConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>
#import <GoogleOpenSource/GoogleOpenSource.h>

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeLoginendpointUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"
// View your basic profile info
GTL_EXTERN NSString * const kGTLAuthScopeLoginendpointUserinfoProfile;  // "https://www.googleapis.com/auth/userinfo.profile"
