/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API

#import "GTLLoginendpointConstants.h"

#import "GTLLoginendpointLoginRequest.h"
#import "GTLLoginendpointLoginResponse.h"

#import "GTLQueryLoginendpoint.h"
#import "GTLServiceLoginendpoint.h"
