/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpointLoginRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLLoginendpointLoginRequest (0 custom class methods, 5 custom properties)

#import "GTLLoginendpointLoginRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLLoginendpointLoginRequest
//

@implementation GTLLoginendpointLoginRequest
@dynamic city, dob, email, gender, preferences;
@end
