/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpointLoginRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLLoginendpointLoginRequest (0 custom class methods, 5 custom properties)

#import <GoogleOpenSource/GoogleOpenSource.h>


// ----------------------------------------------------------------------------
//
//   GTLLoginendpointLoginRequest
//

@interface GTLLoginendpointLoginRequest : GTLObject
@property (nonatomic, copy) NSString *city;
@property (nonatomic, copy) NSString *dob;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *gender;
@property (nonatomic, copy) NSString *preferences;
@end
