/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpointLoginResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLLoginendpointLoginResponse (0 custom class methods, 2 custom properties)

#import <GoogleOpenSource/GoogleOpenSource.h>

// ----------------------------------------------------------------------------
//
//   GTLLoginendpointLoginResponse
//

@interface GTLLoginendpointLoginResponse : GTLObject
@property (nonatomic, copy) NSString *statusCode;
@property (nonatomic, copy) NSString *statusMessage;
@end
