/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLLoginendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API

#import "GTLLoginendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeLoginendpointUserinfoEmail   = @"https://www.googleapis.com/auth/userinfo.email";
NSString * const kGTLAuthScopeLoginendpointUserinfoProfile = @"https://www.googleapis.com/auth/userinfo.profile";
