/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryLoginendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   loginendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryLoginendpoint (1 custom class methods, 1 custom properties)

#import "GTLQueryLoginendpoint.h"

#import "GTLLoginendpointLoginRequest.h"
#import "GTLLoginendpointLoginResponse.h"

@implementation GTLQueryLoginendpoint

@dynamic fields;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryLoginendpoint object.

+ (instancetype)queryForLoginWithObject:(GTLLoginendpointLoginRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"loginendpoint.login";
  GTLQueryLoginendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLLoginendpointLoginResponse class];
  return query;
}

@end
